### ISSUE TITLE
Completion

### ISSUE THREAD

**Issue by micmou** [ForgeEssentials/FERemoteClient#2]
Sorry to bother you about this but any idea when this will be working enough to use?

**Comment by olee** [comment]
Sorry,
I don't have time to work on this until at least 20th of march.
If you want to, feel free to make PRs.
Howerver first thing to do would be adding message-handlers to FE as there are only a few yet.
Take a look here: https://github.com/ForgeEssentials/ForgeEssentialsMain/tree/develop/src/main/java/com/forgeessentials/remote/handler
