### ISSUE TITLE
Cannot add a new server 

### ISSUE THREAD

**Issue by sylphio** [ForgeEssentials/FERemoteClient#5]
when pressing apply or okay, no change are made to the servers.json

**Comment by olee** [comment]
I just tested it and it works without a problem.
As soon as I click "Apply", the json file is changed.

Maybe you don't have write access with Java to the directory where the jar is located?

**Comment by micmou** [comment]
Hmm I had a confusing issue with this as well make sure you have the very first object selected and highlighted. As it is a folder.
